### ISSUE TITLE
"Launch Stack" link is not working

### ISSUE THREAD

**Issue by mstfldmr** [aws-samples/amazon-sagemaker-safe-deployment-pipeline#22]
"Launch Stack" button's link is not working. I get 2 error messages in Cloudformation console.

You must specify a Stack ID. Displaying your Stacks page.
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by brightsparc** [comment]
Resolved this by making the stack public.

If you are looking for AWS Step Functions support, consider running the "Launch Stack" from this branch which will be merged into master shortly.  https://github.com/aws-samples/amazon-sagemaker-safe-deployment-pipeline/tree/sfn-workflow
