### ISSUE TITLE
Custom resources are not deleted

### ISSUE THREAD

**Issue by mstfldmr** [aws-samples/amazon-sagemaker-safe-deployment-pipeline#23]
When I try deleting the following Cloudformation stacks, custom resources are stuck in DELETE_IN_PROGRESS state for long time.

nyctaxi-training-job
nyctaxi-suggest-baseline
nyctaxi-training-job

**Comment by mstfldmr** [comment]
after some time, delete fails with a reason "Custom Resource failed to stabilize in expected time"

**Comment by brightsparc** [comment]
Deleting the training job and baseline calls a custom lambda functions - are you are a check the CloudWatch logs for these lambdas to see if there is any more information.   If they raise an error, cloud formation will be unable to complete the delete operation.   

Note these are being removed in preference for AWS StepFunction integration in the latest branch.

**Comment by brightsparc** [comment]
Closing this issue, as step functions branch has been merged into master that cleans up custom resources.
